version: '2'  

services:
  zabbix_database:
    image: alpine/mariadb
    hostname: zabbix_database
    container_name: zabbix_database
    environment:
      DBNAME: 'zabbix'
      DBUSER: 'zabbix'
      DBPASS: 'ZabbiXPassworD'
    volumes:
      - '/data/mariadb/zabbix:/var/lib/mysql'
    expose:
      - "3306"
    restart: always

  zabbix_server:
    image: alpine/zabbix-server
    hostname: zabbix_server
    container_name: zabbix_server
    expose:
      - "10051"
    restart: always

  zabbix_frontend:
    image: alpine/zabbix-frontend
    hostname: zabbix_frontend
    container_name: zabbix_frontend
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
 
